language: node_js
node_js:
  - "node"
env:
  global:
  - CC_TEST_REPORTER_ID=39f5e52c659b3404a6cb86bfc697ef8255bc7b45dd3deb60c351756aae89852f
cache:
  directories:
    - "node_modules"
services:
       - postgresql
addons:
  chrome: stable
  postgresql: "10"
before_script:
  - psql -c 'create database uggo;' -U postgres
  - psql -c "CREATE USER uggo WITH PASSWORD 'admin';" -U postgres
  - psql -c "CREATE TABLE users (id SERIAL PRIMARY KEY, firstname VARCHAR(30), lastname VARCHAR(30), email VARCHAR(50) NOT NULL, password VARCHAR(40) NOT NULL);" -U postgres
  - psql -c "INSERT INTO users(firstname, lastname, email, password) values('ugo', 'anayo', 'uggoprince@gmail.com', '12345678');" -U postgres
  - psql -c "INSERT INTO users(firstname, lastname, email, password) values('ugo', 'anayo', 'newmanmail@gmail.com', '12345678');" -U postgres
  - npm install nyc
  - curl -L https://codeclimate.com/downloads/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: 
  - npm run coverage
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info