language: node_js
node_js:
  - "node"
env:
  - NODE_ENV=TEST
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: 
  - npm run coverage
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info