language: node_js
node_js:
  - "node"
env:
  - NODE_ENV=TEST
cache:
  directories:
    - "node_modules"
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - nyc --reporter=lcov yarn run unit
after_success: npm run coverage